version: '3'
services:
    server:
        container_name: stylify
        build: .
        working_dir: /usr/share/nginx/html
        volumes:
            - ./.:/usr/share/nginx/html:delegated
        ports:
            - 80:80
            - 81:3000 # Stylify nuxt module playground
        tty: true
