name: Tests

on:
    push:
        branches:
            - '*'
    pull_request:
        branches-ignore:
            - master

jobs:
  tests:
    name: Tests build
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v2

        - uses: actions/setup-node@v3
          with:
            node-version: 16

        - name: Versions
          run: node -v && yarn -v

        - name: Install packages
          run: yarn repo:init

        - name: Build
          run: yarn build

        - name: Eslint
          run: yarn eslint:check

        - name: Jest tests
          run: yarn jest:test+coverage

        - name: 'Upload Artifacts'
          if: ${{ failure() }}
          uses: actions/upload-artifact@v3
          with:
            name: artifacts
            path: |
              packages
              !node_modules
              !packages/*/**/node_modules

        - name: Upload coverage to Codecov
          uses: codecov/codecov-action@v1
          with:
            token: ${{ secrets.CODECOV_TOKEN }}
