name: Tests

on: push

jobs:
  tests:
    name: Tests build
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v2

        - name: Install packages
          run: yarn repo:init

        - name: Build packages
          run: yarn build:all

        - name: Eslint
          run: yarn lint:check

        - name: Jest tests
          run: yarn jest:test

        - name: Upload coverage to Codecov
          uses: codecov/codecov-action@v1
          with:
            token: ${{ secrets.CODECOV_TOKEN }}
