name: Tests

on: push

jobs:
  tests:
    name: Tests build
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v2

        - name: Install packages
          run: yarn repo:init

        - name: Generate types
          run: yarn types

        - name: Build packages
          run: yarn build

        - name: Eslint
          run: yarn eslint:check

        - name: Jest tests
          run: yarn jest:test+coverage

        - name: Upload coverage to Codecov
          uses: codecov/codecov-action@v1
          with:
            token: ${{ secrets.CODECOV_TOKEN }}
